export const CREATORS = [
  { username: 'betweencarpools',      name: 'Between Carpools' },
  { username: 'faigyrabinowitz',      name: 'Faigy Rabinowitz' },
  { username: 'rachelshalam',         name: 'Rachel Shalam' },
  { username: 'alysondweck',          name: 'Alyson Dweck' },
  { username: 'bestmomsfinds',        name: 'Sara-BESTMOMSFINDS' },
  { username: 'themommydictionary',   name: 'Cami Bouskila' },
  { username: 'shimal123',            name: 'Shira Malchi' },
  { username: 'moonlight',            name: 'Aidel Zimmerman' },
  { username: 'twasser',              name: 'Tzili Wasserlauf' },
  { username: 'findsbyrivka',         name: 'Rivka' },
  { username: 'chezchaya',            name: 'Chaya Suzanne Lichtenstein' },
  { username: 'wardrobestaples',      name: 'Nechama Chapler' },
  { username: 'eishesstyle',          name: 'Eliana Sherman' },
  { username: 'thehomezest',          name: 'Elana Marcus' },
  { username: 'familygetup',          name: 'Gita Zaks' },
  { username: 'marblespoon',          name: 'Vera Newman' },
  { username: 'sarahsoliani',         name: 'Sarah Soliani' },
  { username: 'shanilechan',          name: 'Shani Lechan' },
  { username: 'devora',               name: 'Devora Streicher' },
  { username: 'gowncloset',           name: 'Gown Closet' },
  { username: 'rivkirabinowitz',      name: 'Rivki Rabinowitz' },
  { username: 'ladiesshoppinglinks',  name: 'Ladies Shopping Links' },
  { username: 'bigcityshopper',       name: 'BIG CITY SHOPPER' },
  { username: 'styledbynomi',         name: 'Nomi Goldman' },
  { username: 'rachelw',              name: 'Rachel Weisz' },
  { username: 'shiraadar',            name: 'Shira Amir' },
  { username: 'looksbybecs',          name: 'Looks by Becs' },
  { username: 'designerthreads',      name: 'Designer Threads' },
  { username: 'shopwithdass',         name: 'Shop with Dass' },
  { username: 'leahslinks',           name: "Leah's Links" },
  { username: 'yglamm15',             name: 'Little Links' },
  { username: 'chansendz',            name: 'Chan Sendz' },
  { username: 'fitsbyyaf',            name: 'Fits by Yaf' },
  { username: 'shanatoiv',            name: 'Shana Toiv' },
];
